### ISSUE TITLE
`identity` property does not work with string datatype in Python 3.

### ISSUE THREAD

**Issue by melroyrodrigues** [cocagne/zed#1]
After upgrade to python 3, setting a string value to `identity` property raises an exception. This worked perfectly fine in Python 2.

Sample code:
`socket.identity = 'mysocket'`

Traceback:
`
lambda zs,v: zs._zsock.setsockopt(i,totype(v)) )
File "zmq/backend/cython/socket.pyx", line 413, in zmq.backend.cython.socket.Socket.set TypeError: unicode not allowed, use setsockopt_string`

It looks like we need to call `setsockopt_string` instead of `setsockopt` for str datatypes. 

This fix should also be applicable to other string properties in this class - for e.g. `socket.subscribe`.

**Comment by cocagne** [comment]
Hey Melroy. I probably won't be able to get around to fixing this any time
soon but if you guys get to it first and can submit a pull request for
adding Python 3 support I should be able to get it merged relatively
quickly. I can also update the package on pypi.

**Comment by melroyrodrigues** [comment]
Thanks Tom. I just got approval and will open a PR for it soon.

**Comment by melroyrodrigues** [comment]
Hi Tom, i am not able to push my local branch to this repo. Can you check the repo settings once? Thanks!


![image](https://user-images.githubusercontent.com/12142762/170588549-54197980-a737-4e97-854a-9aeaf4a0e0fd.png)

**Comment by cocagne** [comment]
I don't think you need permissions to push directly to my repo. You should
be able to clone it under your github account, push your changes there, and
then open a pull request to my repo. I think that's the standard workflow
for github. Let me know if you run into any issues.

**Comment by melroyrodrigues** [comment]
I figured it out. I created a local branch, made my changes, and was trying to push it to your repo (which i didn't have write access to) I had to fork your repo instead and then make changes directly on master. That seemed to work.
Here is the PR:
https://github.com/cocagne/zed/pull/2

**Comment by cocagne** [comment]
Merged and deployed to pypi as version 1.1.0. Thanks for the pull request Melroy :)

**Comment by melroyrodrigues** [comment]
Thanks Tom for your prompt help! :)

**Comment by cocagne** [comment]
No problem. Thanks for putting up the pull request.
